[[session]]
name = "config"
startup_command = 'tmex -W config "z $(chezmoi source-path) && nvim ."'

[[session]]
name = "linkr"
path = "~/Documents/andrew/dev/linkr"
startup_command = 'tmex -W linkr "nvim ." -w server "pnpm dev"'

[[session]]
name = "ply"
path = "~/Documents/andrew/dev/ply"
startup_command = 'tmex -W ply "nvim ." -w data "mise run data"'

[[session]]
name = "resume-content"
path = "~/Documents/andrew/professional/resumes"
startup_command = 'tmex -W content --layout=2{51} "nvim {}/resume.json" reze -w config "nvim $HOME/.config/reze/reze.toml"'

[[session]]
name = "trmnl/hevy"
path = "~/Documents/andrew/dev/trmnl/plugins/hevy"
startup_command = 'tmex -W trmnl/hevy "nvim ." -w server "mise run server" ; open -g "http://localhost:4567"'

[[session]]
name = "trmnl/climbing-gyms"
path = "~/Documents/andrew/dev/trmnl/plugins/climbing-gym"
startup_command = 'tmex -W trmnl/climbing-gyms "nvim ." -w server "mise run server" ; open -g "http://localhost:4567"'
